# Generated by Django 2.0.3 on 2018-04-02 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("applications", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("sub_industry", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_name", models.CharField(max_length=50)),
                ("is_remote", models.BooleanField()),
                ("min_salary", models.IntegerField()),
                ("max_salary", models.IntegerField()),
                ("tech_stack", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.Company",
                    ),
                ),
            ],
        ),
    ]
